/*
 * This file is generated by jOOQ.
 */
package io.remicro.saga.entities;


import io.remicro.saga.entities.tables.Databasechangeloglock;
import io.remicro.saga.entities.tables.Person;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index DATABASECHANGELOGLOCK_PKEY = Indexes0.DATABASECHANGELOGLOCK_PKEY;
    public static final Index PERSON_NICK_NAME_KEY = Indexes0.PERSON_NICK_NAME_KEY;
    public static final Index PERSON_PKEY = Indexes0.PERSON_PKEY;
    public static final Index PERSON_USER_ID_KEY = Indexes0.PERSON_USER_ID_KEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index DATABASECHANGELOGLOCK_PKEY = Internal.createIndex("databasechangeloglock_pkey", Databasechangeloglock.DATABASECHANGELOGLOCK, new OrderField[] { Databasechangeloglock.DATABASECHANGELOGLOCK.ID }, true);
        public static Index PERSON_NICK_NAME_KEY = Internal.createIndex("person_nick_name_key", Person.PERSON, new OrderField[] { Person.PERSON.NICK_NAME }, true);
        public static Index PERSON_PKEY = Internal.createIndex("person_pkey", Person.PERSON, new OrderField[] { Person.PERSON.ID }, true);
        public static Index PERSON_USER_ID_KEY = Internal.createIndex("person_user_id_key", Person.PERSON, new OrderField[] { Person.PERSON.USER_ID }, true);
    }
}
