/*
 * This file is generated by jOOQ.
 */
package io.remicro.saga.entities;


import io.remicro.saga.entities.tables.Databasechangelog;
import io.remicro.saga.entities.tables.Databasechangeloglock;
import io.remicro.saga.entities.tables.Person;
import io.remicro.saga.entities.tables.Saga;
import io.remicro.saga.entities.tables.Screen;
import io.remicro.saga.entities.tables.Scroll;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1784210382;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.databasechangelog</code>.
     */
    public final Databasechangelog DATABASECHANGELOG = io.remicro.saga.entities.tables.Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>public.databasechangeloglock</code>.
     */
    public final Databasechangeloglock DATABASECHANGELOGLOCK = io.remicro.saga.entities.tables.Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>public.person</code>.
     */
    public final Person PERSON = io.remicro.saga.entities.tables.Person.PERSON;

    /**
     * The table <code>public.saga</code>.
     */
    public final Saga SAGA = io.remicro.saga.entities.tables.Saga.SAGA;

    /**
     * The table <code>public.screen</code>.
     */
    public final Screen SCREEN = io.remicro.saga.entities.tables.Screen.SCREEN;

    /**
     * The table <code>public.scroll</code>.
     */
    public final Scroll SCROLL = io.remicro.saga.entities.tables.Scroll.SCROLL;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Databasechangelog.DATABASECHANGELOG,
            Databasechangeloglock.DATABASECHANGELOGLOCK,
            Person.PERSON,
            Saga.SAGA,
            Screen.SCREEN,
            Scroll.SCROLL);
    }
}
