/*
 * This file is generated by jOOQ.
 */
package io.remicro.saga.entities;


import io.remicro.saga.entities.tables.Databasechangelog;
import io.remicro.saga.entities.tables.Databasechangeloglock;
import io.remicro.saga.entities.tables.Person;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.databasechangelog</code>.
     */
    public static final Databasechangelog DATABASECHANGELOG = io.remicro.saga.entities.tables.Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>public.databasechangeloglock</code>.
     */
    public static final Databasechangeloglock DATABASECHANGELOGLOCK = io.remicro.saga.entities.tables.Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>public.person</code>.
     */
    public static final Person PERSON = io.remicro.saga.entities.tables.Person.PERSON;
}
