/*
 * This file is generated by jOOQ.
 */
package io.remicro.saga.entities.tables.pojos;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;
import io.remicro.saga.entities.tables.interfaces.IPerson;

import java.sql.Timestamp;
import java.util.UUID;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Person implements VertxPojo, IPerson {

    private static final long serialVersionUID = 686212550;

    private UUID      id;
    private String    nickName;
    private String    userId;
    private Timestamp createdAt;
    private Timestamp updatedAt;

    public Person() {}

    public Person(IPerson value) {
        this.id = value.getId();
        this.nickName = value.getNickName();
        this.userId = value.getUserId();
        this.createdAt = value.getCreatedAt();
        this.updatedAt = value.getUpdatedAt();
    }

    public Person(
        UUID      id,
        String    nickName,
        String    userId,
        Timestamp createdAt,
        Timestamp updatedAt
    ) {
        this.id = id;
        this.nickName = nickName;
        this.userId = userId;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    @Override
    public UUID getId() {
        return this.id;
    }

    @Override
    public Person setId(UUID id) {
        this.id = id;
        return this;
    }

    @Override
    public String getNickName() {
        return this.nickName;
    }

    @Override
    public Person setNickName(String nickName) {
        this.nickName = nickName;
        return this;
    }

    @Override
    public String getUserId() {
        return this.userId;
    }

    @Override
    public Person setUserId(String userId) {
        this.userId = userId;
        return this;
    }

    @Override
    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    @Override
    public Person setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    @Override
    public Timestamp getUpdatedAt() {
        return this.updatedAt;
    }

    @Override
    public Person setUpdatedAt(Timestamp updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Person (");

        sb.append(id);
        sb.append(", ").append(nickName);
        sb.append(", ").append(userId);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(IPerson from) {
        setId(from.getId());
        setNickName(from.getNickName());
        setUserId(from.getUserId());
        setCreatedAt(from.getCreatedAt());
        setUpdatedAt(from.getUpdatedAt());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends IPerson> E into(E into) {
        into.from(this);
        return into;
    }

    public Person(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }
}
