/*
 * This file is generated by jOOQ.
 */
package io.remicro.saga.entities.tables.pojos;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;
import io.remicro.saga.entities.tables.interfaces.IScreen;

import java.sql.Timestamp;
import java.util.UUID;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Screen implements VertxPojo, IScreen {

    private static final long serialVersionUID = -455256140;

    private UUID      id;
    private UUID      ownerId;
    private String    original;
    private String    scaled;
    private Timestamp createdAt;
    private Timestamp updatedAt;

    public Screen() {}

    public Screen(IScreen value) {
        this.id = value.getId();
        this.ownerId = value.getOwnerId();
        this.original = value.getOriginal();
        this.scaled = value.getScaled();
        this.createdAt = value.getCreatedAt();
        this.updatedAt = value.getUpdatedAt();
    }

    public Screen(
        UUID      id,
        UUID      ownerId,
        String    original,
        String    scaled,
        Timestamp createdAt,
        Timestamp updatedAt
    ) {
        this.id = id;
        this.ownerId = ownerId;
        this.original = original;
        this.scaled = scaled;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    @Override
    public UUID getId() {
        return this.id;
    }

    @Override
    public Screen setId(UUID id) {
        this.id = id;
        return this;
    }

    @Override
    public UUID getOwnerId() {
        return this.ownerId;
    }

    @Override
    public Screen setOwnerId(UUID ownerId) {
        this.ownerId = ownerId;
        return this;
    }

    @Override
    public String getOriginal() {
        return this.original;
    }

    @Override
    public Screen setOriginal(String original) {
        this.original = original;
        return this;
    }

    @Override
    public String getScaled() {
        return this.scaled;
    }

    @Override
    public Screen setScaled(String scaled) {
        this.scaled = scaled;
        return this;
    }

    @Override
    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    @Override
    public Screen setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    @Override
    public Timestamp getUpdatedAt() {
        return this.updatedAt;
    }

    @Override
    public Screen setUpdatedAt(Timestamp updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Screen (");

        sb.append(id);
        sb.append(", ").append(ownerId);
        sb.append(", ").append(original);
        sb.append(", ").append(scaled);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(IScreen from) {
        setId(from.getId());
        setOwnerId(from.getOwnerId());
        setOriginal(from.getOriginal());
        setScaled(from.getScaled());
        setCreatedAt(from.getCreatedAt());
        setUpdatedAt(from.getUpdatedAt());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends IScreen> E into(E into) {
        into.from(this);
        return into;
    }

    public Screen(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }
}
