/*
 * This file is generated by jOOQ.
 */
package io.remicro.saga.entities.tables.records;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;
import io.remicro.saga.entities.tables.Scroll;
import io.remicro.saga.entities.tables.interfaces.IScroll;

import java.sql.Timestamp;
import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ScrollRecord extends UpdatableRecordImpl<ScrollRecord> implements VertxPojo, Record7<UUID, String, String, Integer, UUID, Timestamp, Timestamp>, IScroll {

    private static final long serialVersionUID = 1251499470;

    /**
     * Setter for <code>public.scroll.id</code>.
     */
    @Override
    public ScrollRecord setId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.scroll.id</code>.
     */
    @Override
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.scroll.title</code>.
     */
    @Override
    public ScrollRecord setTitle(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.scroll.title</code>.
     */
    @Override
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.scroll.desc</code>.
     */
    @Override
    public ScrollRecord setDesc(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.scroll.desc</code>.
     */
    @Override
    public String getDesc() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.scroll.vision</code>.
     */
    @Override
    public ScrollRecord setVision(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.scroll.vision</code>.
     */
    @Override
    public Integer getVision() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.scroll.saga_id</code>.
     */
    @Override
    public ScrollRecord setSagaId(UUID value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.scroll.saga_id</code>.
     */
    @Override
    public UUID getSagaId() {
        return (UUID) get(4);
    }

    /**
     * Setter for <code>public.scroll.created_at</code>.
     */
    @Override
    public ScrollRecord setCreatedAt(Timestamp value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.scroll.created_at</code>.
     */
    @Override
    public Timestamp getCreatedAt() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>public.scroll.updated_at</code>.
     */
    @Override
    public ScrollRecord setUpdatedAt(Timestamp value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.scroll.updated_at</code>.
     */
    @Override
    public Timestamp getUpdatedAt() {
        return (Timestamp) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<UUID, String, String, Integer, UUID, Timestamp, Timestamp> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<UUID, String, String, Integer, UUID, Timestamp, Timestamp> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field1() {
        return Scroll.SCROLL.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Scroll.SCROLL.TITLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Scroll.SCROLL.DESC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Scroll.SCROLL.VISION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field5() {
        return Scroll.SCROLL.SAGA_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return Scroll.SCROLL.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return Scroll.SCROLL.UPDATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getDesc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getVision();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID component5() {
        return getSagaId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDesc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getVision();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value5() {
        return getSagaId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScrollRecord value1(UUID value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScrollRecord value2(String value) {
        setTitle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScrollRecord value3(String value) {
        setDesc(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScrollRecord value4(Integer value) {
        setVision(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScrollRecord value5(UUID value) {
        setSagaId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScrollRecord value6(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScrollRecord value7(Timestamp value) {
        setUpdatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScrollRecord values(UUID value1, String value2, String value3, Integer value4, UUID value5, Timestamp value6, Timestamp value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(IScroll from) {
        setId(from.getId());
        setTitle(from.getTitle());
        setDesc(from.getDesc());
        setVision(from.getVision());
        setSagaId(from.getSagaId());
        setCreatedAt(from.getCreatedAt());
        setUpdatedAt(from.getUpdatedAt());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends IScroll> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ScrollRecord
     */
    public ScrollRecord() {
        super(Scroll.SCROLL);
    }

    /**
     * Create a detached, initialised ScrollRecord
     */
    public ScrollRecord(UUID id, String title, String desc, Integer vision, UUID sagaId, Timestamp createdAt, Timestamp updatedAt) {
        super(Scroll.SCROLL);

        set(0, id);
        set(1, title);
        set(2, desc);
        set(3, vision);
        set(4, sagaId);
        set(5, createdAt);
        set(6, updatedAt);
    }

    public ScrollRecord(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }
}
