/*
 * This file is generated by jOOQ.
 */
package io.remicro.saga.entities.tables.interfaces;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IDatabasechangelog extends VertxPojo, Serializable {

    /**
     * Setter for <code>public.databasechangelog.id</code>.
     */
    public IDatabasechangelog setId(String value);

    /**
     * Getter for <code>public.databasechangelog.id</code>.
     */
    public String getId();

    /**
     * Setter for <code>public.databasechangelog.author</code>.
     */
    public IDatabasechangelog setAuthor(String value);

    /**
     * Getter for <code>public.databasechangelog.author</code>.
     */
    public String getAuthor();

    /**
     * Setter for <code>public.databasechangelog.filename</code>.
     */
    public IDatabasechangelog setFilename(String value);

    /**
     * Getter for <code>public.databasechangelog.filename</code>.
     */
    public String getFilename();

    /**
     * Setter for <code>public.databasechangelog.dateexecuted</code>.
     */
    public IDatabasechangelog setDateexecuted(Timestamp value);

    /**
     * Getter for <code>public.databasechangelog.dateexecuted</code>.
     */
    public Timestamp getDateexecuted();

    /**
     * Setter for <code>public.databasechangelog.orderexecuted</code>.
     */
    public IDatabasechangelog setOrderexecuted(Integer value);

    /**
     * Getter for <code>public.databasechangelog.orderexecuted</code>.
     */
    public Integer getOrderexecuted();

    /**
     * Setter for <code>public.databasechangelog.exectype</code>.
     */
    public IDatabasechangelog setExectype(String value);

    /**
     * Getter for <code>public.databasechangelog.exectype</code>.
     */
    public String getExectype();

    /**
     * Setter for <code>public.databasechangelog.md5sum</code>.
     */
    public IDatabasechangelog setMd5sum(String value);

    /**
     * Getter for <code>public.databasechangelog.md5sum</code>.
     */
    public String getMd5sum();

    /**
     * Setter for <code>public.databasechangelog.description</code>.
     */
    public IDatabasechangelog setDescription(String value);

    /**
     * Getter for <code>public.databasechangelog.description</code>.
     */
    public String getDescription();

    /**
     * Setter for <code>public.databasechangelog.comments</code>.
     */
    public IDatabasechangelog setComments(String value);

    /**
     * Getter for <code>public.databasechangelog.comments</code>.
     */
    public String getComments();

    /**
     * Setter for <code>public.databasechangelog.tag</code>.
     */
    public IDatabasechangelog setTag(String value);

    /**
     * Getter for <code>public.databasechangelog.tag</code>.
     */
    public String getTag();

    /**
     * Setter for <code>public.databasechangelog.liquibase</code>.
     */
    public IDatabasechangelog setLiquibase(String value);

    /**
     * Getter for <code>public.databasechangelog.liquibase</code>.
     */
    public String getLiquibase();

    /**
     * Setter for <code>public.databasechangelog.contexts</code>.
     */
    public IDatabasechangelog setContexts(String value);

    /**
     * Getter for <code>public.databasechangelog.contexts</code>.
     */
    public String getContexts();

    /**
     * Setter for <code>public.databasechangelog.labels</code>.
     */
    public IDatabasechangelog setLabels(String value);

    /**
     * Getter for <code>public.databasechangelog.labels</code>.
     */
    public String getLabels();

    /**
     * Setter for <code>public.databasechangelog.deployment_id</code>.
     */
    public IDatabasechangelog setDeploymentId(String value);

    /**
     * Getter for <code>public.databasechangelog.deployment_id</code>.
     */
    public String getDeploymentId();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IDatabasechangelog
     */
    public void from(io.remicro.saga.entities.tables.interfaces.IDatabasechangelog from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IDatabasechangelog
     */
    public <E extends io.remicro.saga.entities.tables.interfaces.IDatabasechangelog> E into(E into);

    @Override
    public default IDatabasechangelog fromJson(io.vertx.core.json.JsonObject json) {
        setId(json.getString("id"));
        setAuthor(json.getString("author"));
        setFilename(json.getString("filename"));
        // Omitting unrecognized type java.sql.Timestamp for column dateexecuted!
        setOrderexecuted(json.getInteger("orderexecuted"));
        setExectype(json.getString("exectype"));
        setMd5sum(json.getString("md5sum"));
        setDescription(json.getString("description"));
        setComments(json.getString("comments"));
        setTag(json.getString("tag"));
        setLiquibase(json.getString("liquibase"));
        setContexts(json.getString("contexts"));
        setLabels(json.getString("labels"));
        setDeploymentId(json.getString("deployment_id"));
        return this;
    }


    @Override
    public default io.vertx.core.json.JsonObject toJson() {
        io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
        json.put("id",getId());
        json.put("author",getAuthor());
        json.put("filename",getFilename());
        // Omitting unrecognized type java.sql.Timestamp for column dateexecuted!
        json.put("orderexecuted",getOrderexecuted());
        json.put("exectype",getExectype());
        json.put("md5sum",getMd5sum());
        json.put("description",getDescription());
        json.put("comments",getComments());
        json.put("tag",getTag());
        json.put("liquibase",getLiquibase());
        json.put("contexts",getContexts());
        json.put("labels",getLabels());
        json.put("deployment_id",getDeploymentId());
        return json;
    }

}
