/*
 * This file is generated by jOOQ.
 */
package io.remicro.saga.entities.tables.interfaces;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.io.Serializable;
import java.sql.Timestamp;
import java.util.UUID;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ISaga extends VertxPojo, Serializable {

    /**
     * Setter for <code>public.saga.id</code>.
     */
    public ISaga setId(UUID value);

    /**
     * Getter for <code>public.saga.id</code>.
     */
    public UUID getId();

    /**
     * Setter for <code>public.saga.title</code>.
     */
    public ISaga setTitle(String value);

    /**
     * Getter for <code>public.saga.title</code>.
     */
    public String getTitle();

    /**
     * Setter for <code>public.saga.owner_id</code>.
     */
    public ISaga setOwnerId(UUID value);

    /**
     * Getter for <code>public.saga.owner_id</code>.
     */
    public UUID getOwnerId();

    /**
     * Setter for <code>public.saga.created_at</code>.
     */
    public ISaga setCreatedAt(Timestamp value);

    /**
     * Getter for <code>public.saga.created_at</code>.
     */
    public Timestamp getCreatedAt();

    /**
     * Setter for <code>public.saga.updated_at</code>.
     */
    public ISaga setUpdatedAt(Timestamp value);

    /**
     * Getter for <code>public.saga.updated_at</code>.
     */
    public Timestamp getUpdatedAt();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ISaga
     */
    public void from(io.remicro.saga.entities.tables.interfaces.ISaga from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ISaga
     */
    public <E extends io.remicro.saga.entities.tables.interfaces.ISaga> E into(E into);

    @Override
    public default ISaga fromJson(io.vertx.core.json.JsonObject json) {
        // Omitting unrecognized type java.util.UUID for column id!
        setTitle(json.getString("title"));
        // Omitting unrecognized type java.util.UUID for column owner_id!
        // Omitting unrecognized type java.sql.Timestamp for column created_at!
        // Omitting unrecognized type java.sql.Timestamp for column updated_at!
        return this;
    }


    @Override
    public default io.vertx.core.json.JsonObject toJson() {
        io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
        // Omitting unrecognized type java.util.UUID for column id!
        json.put("title",getTitle());
        // Omitting unrecognized type java.util.UUID for column owner_id!
        // Omitting unrecognized type java.sql.Timestamp for column created_at!
        // Omitting unrecognized type java.sql.Timestamp for column updated_at!
        return json;
    }

}
