/*
 * This file is generated by jOOQ.
 */
package io.remicro.saga.entities.tables.interfaces;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.io.Serializable;
import java.sql.Timestamp;
import java.util.UUID;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IScreen extends VertxPojo, Serializable {

    /**
     * Setter for <code>public.screen.id</code>.
     */
    public IScreen setId(UUID value);

    /**
     * Getter for <code>public.screen.id</code>.
     */
    public UUID getId();

    /**
     * Setter for <code>public.screen.owner_id</code>.
     */
    public IScreen setOwnerId(UUID value);

    /**
     * Getter for <code>public.screen.owner_id</code>.
     */
    public UUID getOwnerId();

    /**
     * Setter for <code>public.screen.original</code>.
     */
    public IScreen setOriginal(String value);

    /**
     * Getter for <code>public.screen.original</code>.
     */
    public String getOriginal();

    /**
     * Setter for <code>public.screen.scaled</code>.
     */
    public IScreen setScaled(String value);

    /**
     * Getter for <code>public.screen.scaled</code>.
     */
    public String getScaled();

    /**
     * Setter for <code>public.screen.created_at</code>.
     */
    public IScreen setCreatedAt(Timestamp value);

    /**
     * Getter for <code>public.screen.created_at</code>.
     */
    public Timestamp getCreatedAt();

    /**
     * Setter for <code>public.screen.updated_at</code>.
     */
    public IScreen setUpdatedAt(Timestamp value);

    /**
     * Getter for <code>public.screen.updated_at</code>.
     */
    public Timestamp getUpdatedAt();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IScreen
     */
    public void from(io.remicro.saga.entities.tables.interfaces.IScreen from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IScreen
     */
    public <E extends io.remicro.saga.entities.tables.interfaces.IScreen> E into(E into);

    @Override
    public default IScreen fromJson(io.vertx.core.json.JsonObject json) {
        // Omitting unrecognized type java.util.UUID for column id!
        // Omitting unrecognized type java.util.UUID for column owner_id!
        setOriginal(json.getString("original"));
        setScaled(json.getString("scaled"));
        // Omitting unrecognized type java.sql.Timestamp for column created_at!
        // Omitting unrecognized type java.sql.Timestamp for column updated_at!
        return this;
    }


    @Override
    public default io.vertx.core.json.JsonObject toJson() {
        io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
        // Omitting unrecognized type java.util.UUID for column id!
        // Omitting unrecognized type java.util.UUID for column owner_id!
        json.put("original",getOriginal());
        json.put("scaled",getScaled());
        // Omitting unrecognized type java.sql.Timestamp for column created_at!
        // Omitting unrecognized type java.sql.Timestamp for column updated_at!
        return json;
    }

}
