/*
 * This file is generated by jOOQ.
 */
package io.remicro.saga.entities.tables.interfaces;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.io.Serializable;
import java.sql.Timestamp;
import java.util.UUID;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IScroll extends VertxPojo, Serializable {

    /**
     * Setter for <code>public.scroll.id</code>.
     */
    public IScroll setId(UUID value);

    /**
     * Getter for <code>public.scroll.id</code>.
     */
    public UUID getId();

    /**
     * Setter for <code>public.scroll.title</code>.
     */
    public IScroll setTitle(String value);

    /**
     * Getter for <code>public.scroll.title</code>.
     */
    public String getTitle();

    /**
     * Setter for <code>public.scroll.desc</code>.
     */
    public IScroll setDesc(String value);

    /**
     * Getter for <code>public.scroll.desc</code>.
     */
    public String getDesc();

    /**
     * Setter for <code>public.scroll.vision</code>.
     */
    public IScroll setVision(Integer value);

    /**
     * Getter for <code>public.scroll.vision</code>.
     */
    public Integer getVision();

    /**
     * Setter for <code>public.scroll.saga_id</code>.
     */
    public IScroll setSagaId(UUID value);

    /**
     * Getter for <code>public.scroll.saga_id</code>.
     */
    public UUID getSagaId();

    /**
     * Setter for <code>public.scroll.created_at</code>.
     */
    public IScroll setCreatedAt(Timestamp value);

    /**
     * Getter for <code>public.scroll.created_at</code>.
     */
    public Timestamp getCreatedAt();

    /**
     * Setter for <code>public.scroll.updated_at</code>.
     */
    public IScroll setUpdatedAt(Timestamp value);

    /**
     * Getter for <code>public.scroll.updated_at</code>.
     */
    public Timestamp getUpdatedAt();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IScroll
     */
    public void from(io.remicro.saga.entities.tables.interfaces.IScroll from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IScroll
     */
    public <E extends io.remicro.saga.entities.tables.interfaces.IScroll> E into(E into);

    @Override
    public default IScroll fromJson(io.vertx.core.json.JsonObject json) {
        // Omitting unrecognized type java.util.UUID for column id!
        setTitle(json.getString("title"));
        setDesc(json.getString("desc"));
        setVision(json.getInteger("vision"));
        // Omitting unrecognized type java.util.UUID for column saga_id!
        // Omitting unrecognized type java.sql.Timestamp for column created_at!
        // Omitting unrecognized type java.sql.Timestamp for column updated_at!
        return this;
    }


    @Override
    public default io.vertx.core.json.JsonObject toJson() {
        io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
        // Omitting unrecognized type java.util.UUID for column id!
        json.put("title",getTitle());
        json.put("desc",getDesc());
        json.put("vision",getVision());
        // Omitting unrecognized type java.util.UUID for column saga_id!
        // Omitting unrecognized type java.sql.Timestamp for column created_at!
        // Omitting unrecognized type java.sql.Timestamp for column updated_at!
        return json;
    }

}
