/*
 * This file is generated by jOOQ.
 */
package io.remicro.saga.entities.tables;


import io.remicro.saga.entities.Indexes;
import io.remicro.saga.entities.Keys;
import io.remicro.saga.entities.Public;
import io.remicro.saga.entities.tables.records.SagaRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Saga extends TableImpl<SagaRecord> {

    private static final long serialVersionUID = -146848836;

    /**
     * The reference instance of <code>public.saga</code>
     */
    public static final Saga SAGA = new Saga();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SagaRecord> getRecordType() {
        return SagaRecord.class;
    }

    /**
     * The column <code>public.saga.id</code>.
     */
    public final TableField<SagaRecord, UUID> ID = createField("id", org.jooq.impl.SQLDataType.UUID.nullable(false).defaultValue(org.jooq.impl.DSL.field("uuid_generate_v4()", org.jooq.impl.SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.saga.title</code>.
     */
    public final TableField<SagaRecord, String> TITLE = createField("title", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.saga.owner_id</code>.
     */
    public final TableField<SagaRecord, UUID> OWNER_ID = createField("owner_id", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.saga.created_at</code>.
     */
    public final TableField<SagaRecord, Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("now()", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>public.saga.updated_at</code>.
     */
    public final TableField<SagaRecord, Timestamp> UPDATED_AT = createField("updated_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("now()", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>public.saga</code> table reference
     */
    public Saga() {
        this(DSL.name("saga"), null);
    }

    /**
     * Create an aliased <code>public.saga</code> table reference
     */
    public Saga(String alias) {
        this(DSL.name(alias), SAGA);
    }

    /**
     * Create an aliased <code>public.saga</code> table reference
     */
    public Saga(Name alias) {
        this(alias, SAGA);
    }

    private Saga(Name alias, Table<SagaRecord> aliased) {
        this(alias, aliased, null);
    }

    private Saga(Name alias, Table<SagaRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Saga(Table<O> child, ForeignKey<O, SagaRecord> key) {
        super(child, key, SAGA);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.SAGA_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SagaRecord> getPrimaryKey() {
        return Keys.SAGA_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SagaRecord>> getKeys() {
        return Arrays.<UniqueKey<SagaRecord>>asList(Keys.SAGA_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<SagaRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<SagaRecord, ?>>asList(Keys.SAGA__FK_SAGA_OWNER_PERSON);
    }

    public Person person() {
        return new Person(this, Keys.SAGA__FK_SAGA_OWNER_PERSON);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Saga as(String alias) {
        return new Saga(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Saga as(Name alias) {
        return new Saga(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Saga rename(String name) {
        return new Saga(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Saga rename(Name name) {
        return new Saga(name, null);
    }
}
