/*
 * This file is generated by jOOQ.
 */
package io.remicro.saga.entities.tables;


import io.remicro.saga.entities.Indexes;
import io.remicro.saga.entities.Keys;
import io.remicro.saga.entities.Public;
import io.remicro.saga.entities.tables.records.ScreenRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Screen extends TableImpl<ScreenRecord> {

    private static final long serialVersionUID = 1515839848;

    /**
     * The reference instance of <code>public.screen</code>
     */
    public static final Screen SCREEN = new Screen();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ScreenRecord> getRecordType() {
        return ScreenRecord.class;
    }

    /**
     * The column <code>public.screen.id</code>.
     */
    public final TableField<ScreenRecord, UUID> ID = createField("id", org.jooq.impl.SQLDataType.UUID.nullable(false).defaultValue(org.jooq.impl.DSL.field("uuid_generate_v4()", org.jooq.impl.SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.screen.owner_id</code>.
     */
    public final TableField<ScreenRecord, UUID> OWNER_ID = createField("owner_id", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.screen.original</code>.
     */
    public final TableField<ScreenRecord, String> ORIGINAL = createField("original", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.screen.scaled</code>.
     */
    public final TableField<ScreenRecord, String> SCALED = createField("scaled", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.screen.created_at</code>.
     */
    public final TableField<ScreenRecord, Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("now()", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>public.screen.updated_at</code>.
     */
    public final TableField<ScreenRecord, Timestamp> UPDATED_AT = createField("updated_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("now()", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>public.screen</code> table reference
     */
    public Screen() {
        this(DSL.name("screen"), null);
    }

    /**
     * Create an aliased <code>public.screen</code> table reference
     */
    public Screen(String alias) {
        this(DSL.name(alias), SCREEN);
    }

    /**
     * Create an aliased <code>public.screen</code> table reference
     */
    public Screen(Name alias) {
        this(alias, SCREEN);
    }

    private Screen(Name alias, Table<ScreenRecord> aliased) {
        this(alias, aliased, null);
    }

    private Screen(Name alias, Table<ScreenRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Screen(Table<O> child, ForeignKey<O, ScreenRecord> key) {
        super(child, key, SCREEN);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.SCREEN_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ScreenRecord> getPrimaryKey() {
        return Keys.SCREEN_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ScreenRecord>> getKeys() {
        return Arrays.<UniqueKey<ScreenRecord>>asList(Keys.SCREEN_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ScreenRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ScreenRecord, ?>>asList(Keys.SCREEN__FK_SAGA_OWNER_PERSON);
    }

    public Person person() {
        return new Person(this, Keys.SCREEN__FK_SAGA_OWNER_PERSON);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Screen as(String alias) {
        return new Screen(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Screen as(Name alias) {
        return new Screen(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Screen rename(String name) {
        return new Screen(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Screen rename(Name name) {
        return new Screen(name, null);
    }
}
