/*
 * This file is generated by jOOQ.
 */
package io.remicro.saga.entities.tables.daos;


import io.github.jklingsporn.vertx.jooq.shared.reactive.AbstractReactiveVertxDAO;
import io.remicro.saga.entities.tables.Person;
import io.remicro.saga.entities.tables.records.PersonRecord;

import java.sql.Timestamp;
import java.util.List;
import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Configuration;


import io.vertx.core.Future;
import io.github.jklingsporn.vertx.jooq.classic.reactivepg.ReactiveClassicQueryExecutor;
/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PersonDao extends AbstractReactiveVertxDAO<PersonRecord, io.remicro.saga.entities.tables.pojos.Person, UUID, Future<List<io.remicro.saga.entities.tables.pojos.Person>>, Future<io.remicro.saga.entities.tables.pojos.Person>, Future<Integer>, Future<UUID>> implements io.github.jklingsporn.vertx.jooq.classic.VertxDAO<PersonRecord,io.remicro.saga.entities.tables.pojos.Person,UUID> {

    /**
     * @param configuration Used for rendering, so only SQLDialect must be set and must be one of the POSTGREs types.
     * @param delegate A configured AsyncSQLClient that is used for query execution
     */
    public PersonDao(Configuration configuration, io.reactiverse.pgclient.PgClient delegate) {
        super(Person.PERSON, io.remicro.saga.entities.tables.pojos.Person.class, new ReactiveClassicQueryExecutor<PersonRecord,io.remicro.saga.entities.tables.pojos.Person,UUID>(configuration,delegate,io.remicro.saga.entities.tables.mappers.RowMappers.getPersonMapper()));
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected UUID getId(io.remicro.saga.entities.tables.pojos.Person object) {
        return object.getId();
    }

    /**
     * Find records that have <code>nick_name IN (values)</code> asynchronously
     */
    public Future<List<io.remicro.saga.entities.tables.pojos.Person>> findManyByNickName(List<String> values) {
        return findManyByCondition(Person.PERSON.NICK_NAME.in(values));
    }

    /**
     * Find a unique record that has <code>nick_name = value</code> asynchronously
     */
    public Future<io.remicro.saga.entities.tables.pojos.Person> findOneByNickName(String value) {
        return findOneByCondition(Person.PERSON.NICK_NAME.eq(value));
    }

    /**
     * Find records that have <code>user_id IN (values)</code> asynchronously
     */
    public Future<List<io.remicro.saga.entities.tables.pojos.Person>> findManyByUserId(List<String> values) {
        return findManyByCondition(Person.PERSON.USER_ID.in(values));
    }

    /**
     * Find a unique record that has <code>user_id = value</code> asynchronously
     */
    public Future<io.remicro.saga.entities.tables.pojos.Person> findOneByUserId(String value) {
        return findOneByCondition(Person.PERSON.USER_ID.eq(value));
    }

    /**
     * Find records that have <code>created_at IN (values)</code> asynchronously
     */
    public Future<List<io.remicro.saga.entities.tables.pojos.Person>> findManyByCreatedAt(List<Timestamp> values) {
        return findManyByCondition(Person.PERSON.CREATED_AT.in(values));
    }

    /**
     * Find records that have <code>updated_at IN (values)</code> asynchronously
     */
    public Future<List<io.remicro.saga.entities.tables.pojos.Person>> findManyByUpdatedAt(List<Timestamp> values) {
        return findManyByCondition(Person.PERSON.UPDATED_AT.in(values));
    }

    @Override
    public ReactiveClassicQueryExecutor<PersonRecord,io.remicro.saga.entities.tables.pojos.Person,UUID> queryExecutor(){
        return (ReactiveClassicQueryExecutor<PersonRecord,io.remicro.saga.entities.tables.pojos.Person,UUID>) super.queryExecutor();
    }
}
