/*
 * This file is generated by jOOQ.
 */
package io.remicro.saga.entities.tables.daos;


import io.github.jklingsporn.vertx.jooq.shared.reactive.AbstractReactiveVertxDAO;
import io.remicro.saga.entities.tables.Scroll;
import io.remicro.saga.entities.tables.records.ScrollRecord;

import java.sql.Timestamp;
import java.util.List;
import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Configuration;


import io.vertx.core.Future;
import io.github.jklingsporn.vertx.jooq.classic.reactivepg.ReactiveClassicQueryExecutor;
/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ScrollDao extends AbstractReactiveVertxDAO<ScrollRecord, io.remicro.saga.entities.tables.pojos.Scroll, UUID, Future<List<io.remicro.saga.entities.tables.pojos.Scroll>>, Future<io.remicro.saga.entities.tables.pojos.Scroll>, Future<Integer>, Future<UUID>> implements io.github.jklingsporn.vertx.jooq.classic.VertxDAO<ScrollRecord,io.remicro.saga.entities.tables.pojos.Scroll,UUID> {

    /**
     * @param configuration Used for rendering, so only SQLDialect must be set and must be one of the POSTGREs types.
     * @param delegate A configured AsyncSQLClient that is used for query execution
     */
    public ScrollDao(Configuration configuration, io.reactiverse.pgclient.PgClient delegate) {
        super(Scroll.SCROLL, io.remicro.saga.entities.tables.pojos.Scroll.class, new ReactiveClassicQueryExecutor<ScrollRecord,io.remicro.saga.entities.tables.pojos.Scroll,UUID>(configuration,delegate,io.remicro.saga.entities.tables.mappers.RowMappers.getScrollMapper()));
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected UUID getId(io.remicro.saga.entities.tables.pojos.Scroll object) {
        return object.getId();
    }

    /**
     * Find records that have <code>title IN (values)</code> asynchronously
     */
    public Future<List<io.remicro.saga.entities.tables.pojos.Scroll>> findManyByTitle(List<String> values) {
        return findManyByCondition(Scroll.SCROLL.TITLE.in(values));
    }

    /**
     * Find records that have <code>desc IN (values)</code> asynchronously
     */
    public Future<List<io.remicro.saga.entities.tables.pojos.Scroll>> findManyByDesc(List<String> values) {
        return findManyByCondition(Scroll.SCROLL.DESC.in(values));
    }

    /**
     * Find records that have <code>vision IN (values)</code> asynchronously
     */
    public Future<List<io.remicro.saga.entities.tables.pojos.Scroll>> findManyByVision(List<Integer> values) {
        return findManyByCondition(Scroll.SCROLL.VISION.in(values));
    }

    /**
     * Find records that have <code>saga_id IN (values)</code> asynchronously
     */
    public Future<List<io.remicro.saga.entities.tables.pojos.Scroll>> findManyBySagaId(List<UUID> values) {
        return findManyByCondition(Scroll.SCROLL.SAGA_ID.in(values));
    }

    /**
     * Find records that have <code>created_at IN (values)</code> asynchronously
     */
    public Future<List<io.remicro.saga.entities.tables.pojos.Scroll>> findManyByCreatedAt(List<Timestamp> values) {
        return findManyByCondition(Scroll.SCROLL.CREATED_AT.in(values));
    }

    /**
     * Find records that have <code>updated_at IN (values)</code> asynchronously
     */
    public Future<List<io.remicro.saga.entities.tables.pojos.Scroll>> findManyByUpdatedAt(List<Timestamp> values) {
        return findManyByCondition(Scroll.SCROLL.UPDATED_AT.in(values));
    }

    @Override
    public ReactiveClassicQueryExecutor<ScrollRecord,io.remicro.saga.entities.tables.pojos.Scroll,UUID> queryExecutor(){
        return (ReactiveClassicQueryExecutor<ScrollRecord,io.remicro.saga.entities.tables.pojos.Scroll,UUID>) super.queryExecutor();
    }
}
